Repository Som-Energia/somenergia-generationkwh, pull requests merged in 2020-04, with the labels that each got.

#20 Fix Investment.search() to not include Aportacions
  som_generationkwh/investment.py
  som_generationkwh/tests/investment_tests.py
  som_generationkwh/wizard/wizard_investment_amortization.py
Labels: Aportacions, WIP, bug

#21 Report "Retencions sobre el rendiment de GenerationKWh"
  .gitignore
  som_generationkwh/__terp__.py
  som_generationkwh/amortization_report.xml
  som_generationkwh/i18n/es.po
  som_generationkwh/investment.py
  som_generationkwh/report/__init__.py
  som_generationkwh/report/report_retencions_gkwh.mako
  som_generationkwh/report/report_retencions_gkwh.py
  som_generationkwh/security/ir.model.access.csv
  som_generationkwh/som_generationkwh_data.xml
  som_generationkwh/tests/investment_tests.py
  som_generationkwh/wizard/__init__.py
  som_generationkwh/wizard/wizard_send_retencio_estalvi_to_members.py
  som_generationkwh/wizard/wizard_send_retencio_estalvi_to_members.xml
Labels: enhancement, to be deployed, to be merged

#9 Reaplica ajust autoconsum després de aplicar generation
  som_generationkwh/giscedata_facturacio.py
Labels: deployed in testing, enhancement
