Repository Som-Energia/somenergia-generationkwh, pull requests merged in 2020-06, with the labels that each got.

#29 New boto soci baixa
  som_generationkwh/res_partner.py
  som_generationkwh/somenergia_soci.py
  som_generationkwh/somenergia_soci_view.xml
  som_generationkwh/tests/__init__.py
  som_generationkwh/tests/somenergia_soci_tests.py
Labels: deployed in testing, enhancement, to be merged

#27 Imp move get stats investment generation and remove select
  som_generationkwh/investment.py
  som_generationkwh/tests/investment_tests.py
Labels: bug

#25 ResPartner.www methods considerate APO
  som_generationkwh/investment.py
  som_generationkwh/res_partner.py
  som_generationkwh/tests/__init__.py
  som_generationkwh/tests/generation_data_demo.xml
  som_generationkwh/tests/investment_tests.py
  som_generationkwh/tests/partner_tests.py
Labels: Aportacions

#30 Afegir opció d'enviar correu a la baixa de sòcia
  som_generationkwh/__terp__.py
  som_generationkwh/security/ir.model.access.csv
  som_generationkwh/somenergia_soci.py
  som_generationkwh/somenergia_soci_data.xml
  som_generationkwh/somenergia_soci_view.xml
  som_generationkwh/tests/__init__.py
  som_generationkwh/tests/generation_data_demo.xml
  som_generationkwh/tests/test_wizard_baixa_soci.py
  som_generationkwh/wizard/__init__.py
  som_generationkwh/wizard/wizard_baixa_soci.py
  som_generationkwh/wizard/wizard_baixa_soci.xml
Labels: deployed in testing, enhancement, to be merged
