Repository Som-Energia/somenergia-generationkwh, pull requests merged in 2021-12, with the labels that each got.

#79 Llistat de sòcies per Autoworkers i enviar per email
  som_generationkwh/__terp__.py
  som_generationkwh/wizard/wizard_llibre_registre_socis.py
Labels: Aportacions

#82 Adapt transfer action to APOS
  som_generationkwh/i18n/es_ES.po
  som_generationkwh/i18n/som_generationkwh.pot
  som_generationkwh/investment.py
  som_generationkwh/investment_strategy.py
  som_generationkwh/test/investment_test.py
  som_generationkwh/wizard/wizard_investment_creation.py
  som_generationkwh/wizard/wizard_investment_transfer.py
  som_generationkwh/wizard/wizard_investment_transfer.xml
Labels: enhancement, Aportacions

#83 Check if polissa has gkwh assigment before apply_gkwh
  som_generationkwh/giscedata_facturacio.py
Labels: enhancement
